spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource # 数据源类型
    driver-class-name: com.mysql.cj.jdbc.Driver # 你的数据库驱动
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC # 你的数据库地址
    username: root # 你的数据库用户名
    password: 261615 # 你的数据库密码
  servlet:
    multipart:
      max-file-size: 100MB # 单个文件最大
      max-request-size: 100MB # 总上传大小

application:
  store:
    cos:
      domain-url: https://news-1313478973.cos.ap-chongqing.myqcloud.com # 你的cos域名
      access-key: AKIDNvPxb4MROGC2mT1Uk3KzTp23rY5ShleK # 你的accessKey
      access-key-secret: DNNF0eCQfOfv45vcBdrqgO2eM1iUJOez # 你的accessKeySecret
      bucket: news-1313478973 # 你的bucket
      endpoint: ap-chongqing # 你的地域
    local:
      domain-url: http://localhost:9090 # 你的本地域名

server:
  ip: localhost # 你的ip
  port: 9090 # 你的端口号

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志

files:
  upload:
    path: D:/files/

sms:
  aliyun:
    accessKeyID:  xxx # 你的accessKeyID
    accessKeySecret:  xxx # 你的accessKeySecret
    domain: dysmsapi.aliyuncs.com # 固定不变
    regionId: cn-hangzhou # 固定不变
    templateCode: 你的验证码是 # 你的模板code
    signName: xxx # 你的签名


